server:
  port: 8083

spring:
  application:
    name: e-hub-service
  profiles:
    active: '@spring.profiles.active@'

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO