spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://localhost:5432/e_hub
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
    from: quyenbong02091999@gmail.com
    verify-link: http://localhost:8083/emails/confirm-email
    template-id: d-57fc4e3337164f369d368dd35d8ab7b4

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: e-hub-service
    server: http://localhost:${server.port}
    title: Backend API Document
    version: v1.0.0
